name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Save GITHUB_REF_NAME to file
      run: echo "${{ github.ref_name }}" > ref_name.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ref-name
        path: ref_name.txt 
